# Generated by Django 2.2.12 on 2020-08-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55, verbose_name='Kullanıcı Adınız')),
                ('comment', models.TextField(verbose_name='Yorumunuz')),
            ],
        ),
    ]
